Description: >
    This template deploys a high available ElastiCache cluster
    
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the ElastiCache should be deployed to

    Subnets:
        Description: Choose which subnets the ElastiCache should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    SecurityGroup:
        Description: Select the Security Group to apply to the ElastiCache
        Type: AWS::EC2::SecurityGroup::Id
    
    RedisNodeType:
        Description: Which instance type should we use to build the ElastiCache cluster?
        Type: String
        Default: cache.m3.medium

Resources:

    RedisParameterGroup:
        Type: AWS::ElastiCache::ParameterGroup
        Properties:
            CacheParameterGroupFamily: redis4.0
            Description: RedisParameterGroup
    
    RedisSubnetGroup:
        Type: AWS::ElastiCache::SubnetGroup
        Properties:
            Description: RedisSubnetGroup
            SubnetIds: !Ref Subnets

    RedisReplicationGroup:
        Type: AWS::ElastiCache::ReplicationGroup
        Properties:
            AutomaticFailoverEnabled: true
            CacheNodeType: !Ref RedisNodeType
            CacheParameterGroupName: !Ref RedisParameterGroup
            CacheSubnetGroupName: !Ref RedisSubnetGroup
            Engine: redis
            EngineVersion: 4.0.10
            NumCacheClusters: 2
            ReplicationGroupDescription: RedisReplicationGroup
            SecurityGroupIds:
                - !Ref SecurityGroup
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName
Outputs:

    ElastiCacheCluster:
        Description: A reference to the ElastiCache Cluster
        Value: !Ref RedisReplicationGroup
    ElastiCacheClusterEndpointAddress:
        Description: Redis Endpoint Address
        Value:  !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
    ElastiCacheClusterEndpointPort:
        Description: Redis Endpoint Port
        Value:  !GetAtt RedisReplicationGroup.PrimaryEndPoint.Port


